- name: Install Apache2 without apt module
  hosts: webservers
  become: yes
  
  vars:
    package: apache2
  tasks:

    - name: Update package cache
      shell: apt-get update
      
    - name: show failure
      fail:
        msg: "installatie is mislukt, controleer de packagenaam in het playbook!"
      when: package != "apache2"
      
    - name: Install {{ package }} via shell
      shell: apt-get install -y {{ package }}
      register: install_software
      changed_when: "'ok:' in install_software.stdout or 'Setting up {{ package }}' in install_software.stdout"
    
          
    - name: show setup result
      debug:
        var: install_software
 

    - name: Ensure Apache2 is running
      service:
        name: apache2
        state: started
        enabled: yes