name: VM Deployment with terraform and ansible
on:
  push:
    paths:
      - '**.tf'  # runs only when terraform file is changed
jobs:
  install-webserver:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
       
      - name: run terraform Deployment (test)
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
                 
      - name: Run Ansible Playbook day2operations
        run: |
          ansible-playbook -i inventory.ini day2operations.yml
          
      
          
      