# test simpel terraform destry workflow
name: terraform removal
on:
  workflow_dispatch:
    
jobs:
  run-playbooks:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
       
      - name: run terraform removal (test)
        run: |
          terraform init
          terraform destroy -auto-approve
      
