# test simpel ansible workflow
name: ansible Deployment
on:
  push:
    branches:
      - main  # Change this to your main branch name
jobs:
  run-playbooks:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
       
      - name: run terraform Deployment (test)
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini day2operations.yml
      - name: Test website 
        run: |
          curl http//192.168.1.74
