
name: Terraform Deployment

on:
  push:
    branches:
      - main  # Change this to your main branch name
jobs:
  run-playbooks:
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
       
      - name: Run Ansible Playbook
        run: |
          ansible-playbook install_apache.yml -i localhost, --connection=local
